var index = [
{'name': 'io.vertx.ceylon.sql', 'type': 'package', 'url': 'index.html#section-package', 'doc': '', 'tags': [],'icons': ['icon-package']},
{'name': 'ResultSet.toJson', 'type': 'function', 'url': 'ResultSet.type.html#toJson', 'doc': '', 'tags': [],'icons': ['icon-shared-member', 'icon-decoration-impl']},
{'name': 'ResultSet', 'type': 'class', 'url': 'ResultSet.type.html', 'doc': '<p>Represents the results of a SQL query.\n<p>\nI', 'tags': [],'icons': ['icon-class']},
{'name': 'resultSet.fromJson', 'type': 'function', 'url': 'resultSet.object.html#fromJson', 'doc': '', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'toCeylon.convert', 'type': 'function', 'url': 'resultSet.toCeylon.object.html#convert', 'doc': '', 'tags': [],'icons': ['icon-shared-member', 'icon-decoration-impl']},
{'name': 'toCeylon', 'type': 'object', 'url': 'resultSet.toCeylon.object.html', 'doc': '', 'tags': [],'icons': ['icon-object']},
{'name': 'resultSet.toCeylon', 'type': 'value', 'url': 'resultSet.object.html#toCeylon', 'doc': '', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'toJava.convert', 'type': 'function', 'url': 'resultSet.toJava.object.html#convert', 'doc': '', 'tags': [],'icons': ['icon-shared-member', 'icon-decoration-impl']},
{'name': 'toJava', 'type': 'object', 'url': 'resultSet.toJava.object.html', 'doc': '', 'tags': [],'icons': ['icon-object']},
{'name': 'resultSet.toJava', 'type': 'value', 'url': 'resultSet.object.html#toJava', 'doc': '', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'resultSet.toJson', 'type': 'function', 'url': 'resultSet.object.html#toJson', 'doc': '', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'resultSet', 'type': 'object', 'url': 'resultSet.object.html', 'doc': '', 'tags': [],'icons': ['icon-object']},
{'name': 'resultSet', 'type': 'value', 'url': 'index.html#resultSet', 'doc': '', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'UpdateResult.toJson', 'type': 'function', 'url': 'UpdateResult.type.html#toJson', 'doc': '', 'tags': [],'icons': ['icon-shared-member', 'icon-decoration-impl']},
{'name': 'UpdateResult', 'type': 'class', 'url': 'UpdateResult.type.html', 'doc': '<p>Represents the result of an update/insert/delete operation on the database.\n<p>\nT', 'tags': [],'icons': ['icon-class']},
{'name': 'updateResult.fromJson', 'type': 'function', 'url': 'updateResult.object.html#fromJson', 'doc': '', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'toCeylon.convert', 'type': 'function', 'url': 'updateResult.toCeylon.object.html#convert', 'doc': '', 'tags': [],'icons': ['icon-shared-member', 'icon-decoration-impl']},
{'name': 'toCeylon', 'type': 'object', 'url': 'updateResult.toCeylon.object.html', 'doc': '', 'tags': [],'icons': ['icon-object']},
{'name': 'updateResult.toCeylon', 'type': 'value', 'url': 'updateResult.object.html#toCeylon', 'doc': '', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'toJava.convert', 'type': 'function', 'url': 'updateResult.toJava.object.html#convert', 'doc': '', 'tags': [],'icons': ['icon-shared-member', 'icon-decoration-impl']},
{'name': 'toJava', 'type': 'object', 'url': 'updateResult.toJava.object.html', 'doc': '', 'tags': [],'icons': ['icon-object']},
{'name': 'updateResult.toJava', 'type': 'value', 'url': 'updateResult.object.html#toJava', 'doc': '', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'updateResult.toJson', 'type': 'function', 'url': 'updateResult.object.html#toJson', 'doc': '', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'updateResult', 'type': 'object', 'url': 'updateResult.object.html', 'doc': '', 'tags': [],'icons': ['icon-object']},
{'name': 'updateResult', 'type': 'value', 'url': 'index.html#updateResult', 'doc': '', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'SQLConnection.update', 'type': 'function', 'url': 'SQLConnection.type.html#update', 'doc': '<p>Executes the given SQL statement which may be an <code>INSERT</code>, <code>UPDATE</code>, or <code>DELETE</code>\nstatement.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'SQLConnection.execute', 'type': 'function', 'url': 'SQLConnection.type.html#execute', 'doc': '<p>Executes the given SQL statement</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'SQLConnection.close', 'type': 'function', 'url': 'SQLConnection.type.html#close', 'doc': '<p>Closes the connection.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'SQLConnection.close', 'type': 'function', 'url': 'SQLConnection.type.html#close', 'doc': '<p>Closes the connection.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'SQLConnection.close', 'type': 'function', 'url': 'SQLConnection.type.html#close', 'doc': '<p>Closes the connection.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'SQLConnection.query', 'type': 'function', 'url': 'SQLConnection.type.html#query', 'doc': '<p>Executes the given SQL <code>SELECT</code> statement which returns the results of the query.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'SQLConnection.call', 'type': 'function', 'url': 'SQLConnection.type.html#call', 'doc': '<p>Calls the given SQL <code>PROCEDURE</code> which returns the result from the procedure.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'SQLConnection.rollback', 'type': 'function', 'url': 'SQLConnection.type.html#rollback', 'doc': '<p>Rolls back all changes made since the previous commit/rollback.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'SQLConnection.setAutoCommit', 'type': 'function', 'url': 'SQLConnection.type.html#setAutoCommit', 'doc': '<p>Sets the auto commit flag for this connection.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'SQLConnection.queryWithParams', 'type': 'function', 'url': 'SQLConnection.type.html#queryWithParams', 'doc': '<p>Executes the given SQL <code>SELECT</code> prepared statement which returns the results of the query.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'SQLConnection.commit', 'type': 'function', 'url': 'SQLConnection.type.html#commit', 'doc': '<p>Commits all changes made since the previous commit/rollback.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'SQLConnection.updateWithParams', 'type': 'function', 'url': 'SQLConnection.type.html#updateWithParams', 'doc': '<p>Executes the given prepared statement which may be an <code>INSERT</code>, <code>UPDATE</code>, or <code>DELETE</code>\nstatement with the given parameters</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'SQLConnection.callWithParams', 'type': 'function', 'url': 'SQLConnection.type.html#callWithParams', 'doc': '<p>Calls the given SQL <code>PROCEDURE</code> which returns the result from the procedure.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'SQLConnection', 'type': 'class', 'url': 'SQLConnection.type.html', 'doc': '<p>Represents a connection to a SQL database</p>', 'tags': [],'icons': ['icon-class']},
{'name': 'io.vertx.ceylon.sql', 'type': 'module', 'url': 'index.html', 'doc': '', 'tags': [],'icons': ['icon-module']}];
var tagIndex = [
];
