== Using the file system with Vert.x

The Vert.x `link:../../ceylondoc/vertx-core//file/FileSystem.type.html[FileSystem]` object provides many operations for manipulating the file system.

There is one file system object per Vert.x instance, and you obtain it with  `link:../../ceylondoc/vertx-core//Vertx.type.html#fileSystem()[fileSystem]`.

A blocking and a non blocking version of each operation is provided. The non blocking versions take a handler
which is called when the operation completes or an error occurs.

Here's an example of an asynchronous copy of a file:

[source,ceylon]
----
value fs = vertx.fileSystem();

// Copy file from foo.txt to bar.txt
fs.copy("foo.txt", "bar.txt", (Throwable? res) {
  if (!exists res) {
    // Copied ok!
  } else {
    // Something went wrong
  };
});

----
The blocking versions are named `xxxBlocking` and return the results or throw exceptions directly. In many
cases, depending on the operating system and file system, some of the potentially blocking operations can return
quickly, which is why we provide them, but it's highly recommended that you test how long they take to return in your
particular application before using them from an event loop, so as not to break the Golden Rule.

Here's the copy using the blocking API:

[source,ceylon]
----
value fs = vertx.fileSystem();

// Copy file from foo.txt to bar.txt synchronously
fs.copyBlocking("foo.txt", "bar.txt");

----

Many operations exist to copy, move, truncate, chmod and many other file operations. We won't list them all here,
please consult the `link:../../ceylondoc/vertx-core//file/FileSystem.type.html[API docs]` for the full list.

Let's see a couple of examples using asynchronous methods:

[source,ceylon]
----
import io.vertx.ceylon.core.buffer { buffer } 
import io.vertx.ceylon.core { vertx_ = vertx } 

...

value vertx = vertx_.vertx();

// Read a file
vertx.fileSystem().readFile("target/classes/readme.txt", (Buffer|Throwable result) {
  if (is Buffer result) {
    print(result);
  } else {
    print("Oh oh ...``result``");
  };
});

// Copy a file
vertx.fileSystem().copy("target/classes/readme.txt", "target/classes/readme2.txt", (Throwable? result) {
  if (!exists result) {
    print("File copied");
  } else {
    print("Oh oh ...``result``");
  };
});

// Write a file
vertx.fileSystem().writeFile("target/classes/hello.txt", buffer.buffer("Hello"), (Throwable? result) {
  if (!exists result) {
    print("File written");
  } else {
    print("Oh oh ...``result``");
  };
});

// Check existence and delete
vertx.fileSystem().exists("target/classes/junk.txt", (Boolean|Throwable result) {
  if (is Boolean result && result) {
    vertx.fileSystem().delete("target/classes/junk.txt", (Throwable? r) {
      print("File deleted");
    });
  } else {
    print("Oh oh ... - cannot delete the file: ``result``");
  };
});

----

=== Asynchronous files

Vert.x provides an asynchronous file abstraction that allows you to manipulate a file on the file system.

You open an `link:../../ceylondoc/vertx-core//file/AsyncFile.type.html[AsyncFile]` as follows:

[source,ceylon]
----
value options = OpenOptions();
fileSystem.open("myfile.txt", options, (AsyncFile|Throwable res) {
  if (is AsyncFile res) {
    value file = res;
  } else {
    // Something went wrong!
  };
});

----

`AsyncFile` implements `ReadStream` and `WriteStream` so you can _pump_
files to and from other stream objects such as net sockets, http requests and responses, and WebSockets.

They also allow you to read and write directly to them.

==== Random access writes

To use an `AsyncFile` for random access writing you use the
`link:../../ceylondoc/vertx-core//file/AsyncFile.type.html#write(io.vertx.core.buffer.Buffer,%20long,%20io.vertx.core.Handler)[write]` method.

The parameters to the method are:

* `buffer`: the buffer to write.
* `position`: an integer position in the file where to write the buffer. If the position is greater or equal to the size
 of the file, the file will be enlarged to accommodate the offset.
* `handler`: the result handler

Here is an example of random access writes:

[source,ceylon]
----
import io.vertx.ceylon.core.buffer { buffer } 
import io.vertx.ceylon.core { vertx_ = vertx } 

...

value vertx = vertx_.vertx();
vertx.fileSystem().open("target/classes/hello.txt", OpenOptions(), (AsyncFile|Throwable result) {
  if (is AsyncFile result) {
    value file = result;
    value buff = buffer.buffer("foo");
    variable value i = 0;
    while (i < 5) {
      file.write(buff, buff.length() * i, (Throwable? ar) {
        if (!exists ar) {
          print("Written ok!");
          // etc
        } else {
          print("Failed to write: ``ar``");
        };
      });
      i++};
  } else {
    print("Cannot open file ``result``");
  };
});

----

==== Random access reads

To use an `AsyncFile` for random access reads you use the
`link:../../ceylondoc/vertx-core//file/AsyncFile.type.html#read(io.vertx.core.buffer.Buffer,%20int,%20long,%20int,%20io.vertx.core.Handler)[read]`
method.

The parameters to the method are:

* `buffer`: the buffer into which the data will be read.
* `offset`: an integer offset into the buffer where the read data will be placed.
* `position`: the position in the file where to read data from.
* `length`: the number of bytes of data to read
* `handler`: the result handler

Here's an example of random access reads:

[source,ceylon]
----
import io.vertx.ceylon.core.buffer { buffer } 
import io.vertx.ceylon.core { vertx_ = vertx } 

...

value vertx = vertx_.vertx();
vertx.fileSystem().open("target/classes/les_miserables.txt", OpenOptions(), (AsyncFile|Throwable result) {
  if (is AsyncFile result) {
    value file = result;
    value buff = buffer.buffer(1000);
    variable value i = 0;
    while (i < 10) {
      file.read(buff, i * 100, i * 100, 100, (Buffer|Throwable ar) {
        if (is Buffer ar) {
          print("Read ok!");
        } else {
          print("Failed to write: ``ar``");
        };
      });
      i++};
  } else {
    print("Cannot open file ``result``");
  };
});

----

==== Opening Options

When opening an `AsyncFile`, you pass an `link:../../ceylondoc/vertx-core//file/OpenOptions.type.html[OpenOptions]` instance.
These options describe the behavior of the file access. For instance, you can configure the file permissions with the
`link:../../ceylondoc/vertx-core//file/OpenOptions.type.html#setRead(boolean)[read]`, `link:../../ceylondoc/vertx-core//file/OpenOptions.type.html#setWrite(boolean)[write]`
and `link:../../ceylondoc/vertx-core//file/OpenOptions.type.html#setPerms(java.lang.String)[perms]` methods.

You can also configure the behavior if the open file already exists with
`link:../../ceylondoc/vertx-core//file/OpenOptions.type.html#setCreateNew(boolean)[createNew]` and
`link:../../ceylondoc/vertx-core//file/OpenOptions.type.html#setTruncateExisting(boolean)[truncateExisting]`.

You can also mark the file to be deleted on
close or when the JVM is shutdown with `link:../../ceylondoc/vertx-core//file/OpenOptions.type.html#setDeleteOnClose(boolean)[deleteOnClose]`.

==== Flushing data to underlying storage.

In the `OpenOptions`, you can enable/disable the automatic synchronisation of the content on every write using
`link:../../ceylondoc/vertx-core//file/OpenOptions.type.html#setDsync(boolean)[dsync]`. In that case, you can manually flush any writes from the OS
cache by calling the `link:../../ceylondoc/vertx-core//file/AsyncFile.type.html#flush()[flush]` method.

This method can also be called with an handler which will be called when the flush is complete.

==== Using AsyncFile as ReadStream and WriteStream

`AsyncFile` implements `ReadStream` and `WriteStream`. You can then
use them with a _pump_ to pump data to and from other read and write streams. For example, this would
copy the content to another `AsyncFile`:

[source,ceylon]
----
import io.vertx.ceylon.core { vertx_ = vertx } 
import io.vertx.ceylon.core.streams { pump } 

...

value vertx = vertx_.vertx();
value output = vertx.fileSystem().openBlocking("target/classes/plagiary.txt", OpenOptions());

vertx.fileSystem().open("target/classes/les_miserables.txt", OpenOptions(), (AsyncFile|Throwable result) {
  if (is AsyncFile result) {
    value file = result;
    pump.pump(file, output).start();
    file.endHandler(() {
      print("Copy done");
    });
  } else {
    print("Cannot open file ``result``");
  };
});

----

You can also use the _pump_ to write file content into HTTP responses, or more generally in any
`WriteStream`.

[[classpath]]
==== Accessing files from the classpath

When vert.x cannot find the file on the filesystem it tries to resolve the
file from the class path. Note that classpath resource paths never start with
a `/`. 

Due to the fact that Java does not offer async access to classpath
resources, the file is copied to the filesystem in a worker thread when the
classpath resource is accessed the very first time and served from there
asynchrously. When the same resource is accessed a second time, the file from
the filesystem is served directly from the filesystem. The original content
is served even if the classpath resource changes (e.g. in a development
system). 

This caching behaviour can be disabled by setting the system
property `vertx.disableFileCaching` to `true`. The path where the files are
cached is `.vertx` by default and can be customized by setting the system
property `vertx.cacheDirBase`.

The whole classpath resolving feature can be disabled by setting the system
property `vertx.disableFileCPResolving` to `true`.

==== Closing an AsyncFile

To close an `AsyncFile` call the `link:../../ceylondoc/vertx-core//file/AsyncFile.type.html#close()[close]` method. Closing is asynchronous and
if you want to be notified when the close has been completed you can specify a handler function as an argument.