var index = [
{'name': 'io.vertx.ceylon.auth.shiro', 'type': 'package', 'url': 'index.html#section-package', 'doc': '', 'tags': [],'icons': ['icon-package']},
{'name': 'ShiroAuthOptions.toJson', 'type': 'function', 'url': 'ShiroAuthOptions.type.html#toJson', 'doc': '', 'tags': [],'icons': ['icon-shared-member', 'icon-decoration-impl']},
{'name': 'ShiroAuthOptions', 'type': 'class', 'url': 'ShiroAuthOptions.type.html', 'doc': '<p>Shiro auth configuration options, see Vert.x Auth Shiro component and/or Apache Shiro project.</p>', 'tags': [],'icons': ['icon-class']},
{'name': 'shiroAuthOptions.fromJson', 'type': 'function', 'url': 'shiroAuthOptions.object.html#fromJson', 'doc': '', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'toJava.convert', 'type': 'function', 'url': 'shiroAuthOptions.toJava.object.html#convert', 'doc': '', 'tags': [],'icons': ['icon-shared-member', 'icon-decoration-impl']},
{'name': 'toJava', 'type': 'object', 'url': 'shiroAuthOptions.toJava.object.html', 'doc': '', 'tags': [],'icons': ['icon-object']},
{'name': 'shiroAuthOptions.toJava', 'type': 'value', 'url': 'shiroAuthOptions.object.html#toJava', 'doc': '', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'shiroAuthOptions.toJson', 'type': 'function', 'url': 'shiroAuthOptions.object.html#toJson', 'doc': '', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'shiroAuthOptions', 'type': 'object', 'url': 'shiroAuthOptions.object.html', 'doc': '', 'tags': [],'icons': ['icon-object']},
{'name': 'shiroAuthOptions', 'type': 'value', 'url': 'index.html#shiroAuthOptions', 'doc': '', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'ShiroAuthRealmType', 'type': 'class', 'url': 'ShiroAuthRealmType.type.html', 'doc': '<p>The type of the Shiro auth realm</p>', 'tags': [],'icons': ['icon-class', 'icon-decoration-abstract', 'icon-decoration-enumerated']},
{'name': 'properties', 'type': 'object', 'url': 'properties.object.html', 'doc': '<p>The realm is a Shiro properties auth provider</p>', 'tags': [],'icons': ['icon-object']},
{'name': 'properties', 'type': 'value', 'url': 'index.html#properties', 'doc': '<p>The realm is a Shiro properties auth provider</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'ldap', 'type': 'object', 'url': 'ldap.object.html', 'doc': '<p>The realm is a Shiro LDAP auth provider</p>', 'tags': [],'icons': ['icon-object']},
{'name': 'ldap', 'type': 'value', 'url': 'index.html#ldap', 'doc': '<p>The realm is a Shiro LDAP auth provider</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'shiroAuthRealmType.toString', 'type': 'function', 'url': 'shiroAuthRealmType.object.html#toString', 'doc': '', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'shiroAuthRealmType.fromString', 'type': 'function', 'url': 'shiroAuthRealmType.object.html#fromString', 'doc': '', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'toJava.convert', 'type': 'function', 'url': 'shiroAuthRealmType.toJava.object.html#convert', 'doc': '', 'tags': [],'icons': ['icon-shared-member', 'icon-decoration-impl']},
{'name': 'toJava', 'type': 'object', 'url': 'shiroAuthRealmType.toJava.object.html', 'doc': '', 'tags': [],'icons': ['icon-object']},
{'name': 'shiroAuthRealmType.toJava', 'type': 'value', 'url': 'shiroAuthRealmType.object.html#toJava', 'doc': '', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'toCeylon.convert', 'type': 'function', 'url': 'shiroAuthRealmType.toCeylon.object.html#convert', 'doc': '', 'tags': [],'icons': ['icon-shared-member', 'icon-decoration-impl']},
{'name': 'toCeylon', 'type': 'object', 'url': 'shiroAuthRealmType.toCeylon.object.html', 'doc': '', 'tags': [],'icons': ['icon-object']},
{'name': 'shiroAuthRealmType.toCeylon', 'type': 'value', 'url': 'shiroAuthRealmType.object.html#toCeylon', 'doc': '', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'shiroAuthRealmType', 'type': 'object', 'url': 'shiroAuthRealmType.object.html', 'doc': '', 'tags': [],'icons': ['icon-object']},
{'name': 'shiroAuthRealmType', 'type': 'value', 'url': 'index.html#shiroAuthRealmType', 'doc': '', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'ShiroAuth.setRolePrefix', 'type': 'function', 'url': 'ShiroAuth.type.html#setRolePrefix', 'doc': '<p>Set the role prefix to distinguish from permissions when checking for isPermitted requests.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'ShiroAuth', 'type': 'class', 'url': 'ShiroAuth.type.html', 'doc': '<p>Factory interface for creating Apache Shiro based <code>io.vertx.ext.auth.AuthProvider</code> instances.</p>', 'tags': [],'icons': ['icon-class']},
{'name': 'shiroAuth.create', 'type': 'function', 'url': 'shiroAuth.object.html#create', 'doc': '<p>Create a Shiro auth provider</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'shiroAuth.create', 'type': 'function', 'url': 'shiroAuth.object.html#create', 'doc': '<p>Create a Shiro auth provider</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'shiroAuth.create', 'type': 'function', 'url': 'shiroAuth.object.html#create', 'doc': '<p>Create a Shiro auth provider</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'shiroAuth', 'type': 'object', 'url': 'shiroAuth.object.html', 'doc': '', 'tags': [],'icons': ['icon-object']},
{'name': 'shiroAuth', 'type': 'value', 'url': 'index.html#shiroAuth', 'doc': '', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'io.vertx.ceylon.auth.shiro', 'type': 'module', 'url': 'index.html', 'doc': '', 'tags': [],'icons': ['icon-module']}];
var tagIndex = [
];
